### ISSUE TITLE
Add Cloud Foundry configuration

### ISSUE THREAD

**Issue by froi** [GSA/code-gov-harvester#4]
**Is your feature request related to a problem? Please describe.**
This project will be running on a Cloud Foundry instance, as such configuration for this environment is needed.

**Describe the solution you'd like**
Add a `manifest.yml` file similar to the one found in [code-gov-api](https://github.com/GSA/code-gov-api/blob/master/manifest.yml)

**Describe alternatives you've considered**
Have the Cloud Foundry configuration live in the CircleCI config. This can be done by adding the config values to the `cf push` command. This is not Ideal IMO.

**Additional context**
The `manifest.yml` file is used to configure the runtime of the application in Cloud Foundry.

**Comment by froi** [comment]
Hello Code.gov team @saracope @jcastle @AminPIC.

I was browsing around and noticed that this issues was still open. This should have been closed when the [manifest.yml file](https://github.com/GSA/code-gov-harvester/blob/master/manifest.yml) was added. All Cloud.gov configuration should be there. 😃

**Comment by bjbhattGSA** [comment]
As per Froi's comment above and updated manifest.yml with emailing and cflinuxfs3 stack, this issues can be closed.
